### ISSUE TITLE
Will any checkpoints be released later?

### ISSUE THREAD

**Issue by caopulan** [autonomousvision/stylegan-t#8] opened 2023-04-07 09:25 UTC
Thanks for your great job, I'm wondering will any checkpoints be released later and what is the visual performance of lightweight generator.

**Comment by andzejsp** [comment] 2023-04-07 09:38
so basically you made a car but we got to source gas to run it?

Can someone make sample model for us to test on our poormans systems? Or maybe someone is capable to write step by step what to do in order to make your own data set and run it?.. Ill try to figure this out cuz im jus a nobody

Thanks

**Comment by gcrois** [comment] 2023-04-09 03:13
[It looks like weights will not be released in this repo](https://github.com/autonomousvision/stylegan-t/issues/6#issuecomment-1465375896), but [there is allegedly an open source reproduction of this project + the weights in the works?](https://twitter.com/AxSauer/status/1644264940218327042?s=20)

**Comment by andzejsp** [comment] 2023-04-09 06:27
Hopefully it will be released before stability AI goes under. Fingers crossed

**Comment by xl-sr** [comment] 2023-04-11 08:58
As mentioned above, we won't be able to share weights for this project.
But the next generation will be fully open-source, including the weights :)

**Closed as completed by xl-sr** 2023-04-11 08:58 UTC

**Comment by WyattAutomation** [comment] 2023-04-17 20:25
Someone who is keeping StyleGAN-similar GANs alive (Axel), joining StabilityAI, is actually probably the best news I have read for the advancement of open source GAN generators in a good while; didn't know about this until I saw this thread.  Congrats and thank you for your contributions!  Looking forward to seeing your ongoing work.
