### ISSUE TITLE
🤔

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [autonomousvision/stylegan-t#6] opened 2023-03-12 15:03 UTC
It's a meme by now

https://github.com/autonomousvision/stylegan-t/issues/3

![image](https://user-images.githubusercontent.com/15908060/224553309-91d14df8-6b2f-48d8-86d9-9c2cbf7774b0.png)

**Comment by Jainam213** [comment] 2023-03-12 16:42
At this rate our open source version of gigagan will be done 😂

**Comment by WyattAutomation** [comment] 2023-03-12 20:22
Deepfloyd can't do interactive generation, and I hope you have a multimillion dollar GPU cluster to train your GigaGAN clone on.

Be patient; the author can release this whenever they want, and they certainly aren't obligated to if you all are being rude about it.

**Comment by Jainam213** [comment] 2023-03-12 20:31
I was immature sorry

**Comment by FrancescoSaverioZuppichini** [comment] 2023-03-12 22:30
@WyattAutomation is not being rude, it's just interesting to be excited by something everybody is sharing but we only have cherry-picked images in the paper - I am genually asking why people publish a paper that was supposedly done with code and then they don't publish the code - and that's a meme, it happens all the time 

Btw, if you need help to unspaghetti the code - feel free to ping me by email francesco.zuppichini@gmail.com - happy to contribute :smile: 

Spinning up my server, I'll let you know if it runs crysis

**Comment by xl-sr** [comment] 2023-03-13 01:34
Several points:

- I locked the issue, so people watching the repo wouldn't get annoyed by the notifications. I actually think it's funny, and I am happy that people are excited.
- If you check my previous projects, code was released for ALL of them eventually; sometimes it just takes time (other projects, long-due vacation, etc.)
- Disappointing news (to manage expectations): Unfortunately, we will not share pretrained weights, only code. 
- Good news: I will be involved in a fully open-source reproduction effort, and weights will be shared. It'll just take some more time.

**Comment by Warlord-K** [comment] 2023-03-13 17:59
Absolutely Excited for the Code!

**Comment by chrisbward** [comment] 2023-03-15 11:39
Vaporware

**Comment by WyattAutomation** [comment] 2023-03-18 05:30
I can't lie I was just as excited as the rest of these folks, I just didn't want to be a pest about it.  Didn't mean to offend anyone, I have been watching this repo pretty closely and I wanted to ask about it every single time and forced myself not to.

I am assuming there are new EU policies governing Open Source Generative models that the organization that helped fund this work is concerned about; perhaps not, it just seems like this is a reasonable assumption to make.

Your news makes me feel several different ways, and I am going to do my best to stay as optimistic as possible upon reading it:

First of all, I am quite happy to hear that the code is being released.  At the very core of this technology, even if I will never have anywhere close to financial resources required to train it, it sounds like we all still will not be locked out of the underlying technology and the highly valuable knowledge-sharing that code facilitates.  That is the most important part to me; not being "locked out".

Secondly, I am absolutely terrified by recent events on the regulation of GPAI, and the existential threat that poses to the future of innovation across the entirety of the western world.

I have been working at my dream job as a Senior SWE in ML/CV in Simulation and Robotics for a Fortune 100 company for many years now.  I live a very good life and I am thriving in both my career and life outside of it.  I am a high-performer that loves what they do for work, and who is compensated well for consistently delivering results.

I only mention any of that because unlike most of my peers, I don't have my master's degree or PhD in a STEM related field.  

My undergrad is in Parks and Recreation, and I have never leveraged it for work.  About a decade and a half or so ago, I was a dishwasher/line cook that could barely afford to survive.  I spent a lot of time playing music and drinking with friends, and inadvertently built up a knack for troubleshooting Ableton Live on Windows, which prompted me to get a job as a helpdesk technician at a small IT company.

I got stuck in dead-end wages there for a couple years; I got by but I still struggled.  That company did however have the opportunity to work up to software engineering, which I had tried for about a year and just couldn't force myself to stick to it.

That was the case up until I stumbled upon YOLO (object detection) online.  That was the first real exposure I had to AI, and it lit a fire under me.  I started spending 5 or 6 hours a night after 12-hour work days hunting down pretrained weights, writing scripts and classes and then simple UI utilities for webscraping, and labeling images, utilities for downloading and prepping existing datasets and formatting it for training YOLO.  I started ordering robotics parts, ARM SOCs, and developing apps for object detection in RTSP video feeds, which lead to me into a gold mine of valuable projects back at work with my company's existing manufacturing clients.  I went from setting up PC's in dentist's offices to engineering applications for further automating massive production operations in ways that literally no IT company on this half of the continent could compete with at the time.  I went from barely being able to do a hello world in C# to applied computer vision, leveraging customizable machine learning solutions in everything from Django running in k8s with React on the front-end to leveraging ROS2's realtime DDS pubsub as an idustrial middleware framework for integrating these solutions all the way to and through the microcontroller.

After about 6 years of that I started getting offers for extremely lucrative consulting contracts and went out on my own.  Made a bunch of money in a short time just as a consultant and individual contributor; went from 12 hour+ days working for someone else, to 4 day weeks and 6 hour days making about 5 times my previous salary.  Eventually this led me into my current job, making meaningful contributions at a level that I never in my wildest dreams thought I could have reached; not just on income but in implementation.. but here we are..

...now, why am I telling you all this?.. why does this matter?

Because if technology like YOLO had not have been freely, and openly shared for public use, I would have never done any of those things. 

I would not have contributed almost a decade of meaningful contributions to both small, medium, and enterprise companies, I would not have been able to help countless coworkers and people that consulted with me along the way to deliver on successes that improved every individual team member's standing, compensation, and lasting success on the job and outside of it.  Most importantly I would not have found the motivation and technical/business acumen needed for me to find my dream job, to buy the home I always dreamed of owning, or to develop well enough as a person to find/marry the love of my life along they way.  

I apologize for the life story on an issues thread, but I cannot express with words the degree to which having direct, uninhibited, free access to state of the art and fully working Machine Learning technology has had on transforming my quality of life.  Everything I own and everything I am, I owe to the brilliance and benevolence of an open source community of the world's greatest minds working together for one simple purpose:

To make life better for as many people as possible  through the free exchange of ideas, information, and discoveries at the bleeding edge of innovation.

When I first understood the value of FOSS, it was when I downloaded the weights and code and ran that first detection model on salvaged desktop hardware and a used $5 usb web cam from a thrift store.  

The realization that I held in my own two hands, a technology that could (and did) empower countless successes in my own life, with ZERO paywall or "ethics" committee or academic policy or lobbied regulatory capture or other price-gouged socioeconomic tyrant gatekeeping or excluding me from leveraging it in any way I needed.. and that it was running *perfectly* on parts of 5+ year old computers that I LITERALLY pulled out of the trash behin my work.. 

That was the most incomprehensibly valuable realization I have ever had in my life.  I finally OWNED something with real, lasting value.  I didn't own my car, I didn't own my home, all of my work clothes and everything else I had paid for on credit cards that would have taken 17 years of payments to pay off.  I had medical debt, debt from school, debt from work.  I didn't own the money that paid to keep myself alive, which feels a lot like not even owning your own body (not being able to afford going to the doctor in the US is a common thing and it really sucks).  Through all of that, FOSS pulled through and was the tool of liberation I was able to use to claw my way out of a designed system of hopelessness, depression, and poverty.

I am so sorry for posting all of that, but these new laws that suggest banning the sharing of open source Machine Learning is the most terrifying news that I have heard in recent years.  How many others like myself will this policy cause to lose access to the same tools I was able to leverage to escape a world that is overwhelmed with regulation that SOLELY benefits the hoarded wealth of billionaires at the expense of the rest of the world?

I am eternally grateful for your work, and I am nearing a point where it is time to begin planning on how we need to respond to the restriction of emerging technologies to keep them in the hands of the people, and away from exclusive access by entities that seek the ill-gotten gains of regulatory capture.

Sorry for the long story here, and I look forward to reviewing the code upon it's release.  I hope this doesn't come off as too heated, I just want to get through to as many important peers in the field as possible on how much these changes in policy have the potential to harm a global public, or at the very least to share my own small story to convey the magnitude of the devastation that restrictive policies on this technology without a doubt would have had on my own life.  Global prosperity depends on continuing to openly exchange the most valuable of ideas; I am here and willing to help however I can to ensure we don't lose that.

**Comment by WyattAutomation** [comment] 2023-03-18 15:35
I feel embarrassed making such a long post but I need somewhere to vent and have nowhere else that makes sense to do this, so I am putting this back up.  Sorry in advance, sorry if this makes me look like a crazy person but the recent trend of withholding of Open Source models is devastating, even though I am thankful for the resilience of the community and your work here.

anyway..

I can't lie I was just as excited as the rest of these folks, I just didn't want to be a pest about it.  Didn't mean to offend anyone, I have been watching this repo pretty closely and I wanted to ask about it every single time and forced myself not to.

I am assuming there are new EU policies governing Open Source Generative models that the organization that helped fund this work is concerned about; perhaps not, it just seems like this is a reasonable assumption to make.

Your news makes me feel several different ways, and I am going to do my best to stay as optimistic as possible upon reading it:

First of all, I am quite happy to hear that the code is being released.  At the very core of this technology, even if I will never have anywhere close to the financial resources required to train it, it sounds like we all still will not be locked out of the underlying technology and the highly valuable knowledge-sharing that code facilitates.  That is the most important part to me; not being "locked out".

Secondly, I am absolutely terrified by recent events on the regulation of GPAI, and the existential threat that poses to the future of innovation across the entirety of the western world.

I have been working at my dream job as a Senior SWE in a Fortune 100 company for several years now, and I am involved regularly in ML/CV in Simulation and Robotics engineering efforts.  I live a very good life and I am thriving in both my career and life outside of it.  I am a high-performer that loves what they do for work, and who is compensated well for consistently delivering results.

I only mention any of that because unlike most of my peers, I don't have my master's degree or PhD in a STEM related field.  

My undergrad is in Parks and Recreation, and I have never leveraged it for work.  About a decade and a half or so ago, I was a dishwasher/line cook that could barely afford to survive.  I spent a lot of time playing music and drinking with friends, and inadvertently built up a knack for troubleshooting Ableton Live on Windows, which prompted me to get a job as a helpdesk technician at a small IT company.

I got stuck in dead-end wages there for a couple years; I got by but I still struggled.  That company did however have the opportunity to work up to software engineering, which I had tried for about a year and just couldn't force myself to stick to it.

That was the case up until I stumbled upon YOLO (object detection) online.  That was the first real exposure I had to AI, and it lit a fire under me.  I started spending 5 or 6 hours a night after 12-hour work days hunting down pretrained weights, writing scripts and classes and then simple UI utilities for webscraping, and labeling images, utilities for downloading and prepping existing datasets and formatting it for training YOLO.  I started ordering robotics parts, ARM SOCs, and developing apps for object detection in RTSP video feeds, which lead to me into a gold mine of valuable projects back at work with my company's existing manufacturing clients.  I went from setting up PC's in dentist's offices to engineering applications for further automating massive production operations in ways that literally no IT company on this half of the continent could compete with at the time.  I went from barely being able to do a hello world in C# to applied computer vision, leveraging customizable machine learning solutions in everything from Django running in k8s with React on the front-end to leveraging ROS2's realtime DDS pubsub as an idustrial middleware framework for integrating these solutions all the way to and through the microcontroller.

After about 6 years of that I started getting offers for extremely lucrative consulting contracts and went out on my own.  Made a bunch of money in a short time just as a consultant and individual contributor; went from 12 hour+ days working for someone else, to 4 day weeks and 6 hour days making about 5 times my previous salary.  Eventually this led me into my current job, making meaningful contributions at a level that I never in my wildest dreams thought I could have reached; not just on income but in implementation.. but here we are..

...now, why am I telling you all this?.. why does this matter?

Because if technology like YOLO had not have been freely, and openly shared for public use, I would have never done any of those things. 

I would not have contributed almost a decade of meaningful contributions to both small, medium, and enterprise companies, I would not have been able to help countless coworkers and people that consulted with me along the way to deliver on successes that improved every individual team member's standing, compensation, and lasting success on the job and outside of it.  Most importantly I would not have found the motivation and technical/business acumen needed for me to find my dream job, to buy the home I always dreamed of owning, or to develop well enough as a person to find/marry the love of my life along they way.  

I apologize for the life story on an issues thread, but I cannot express with words the degree to which having direct, uninhibited, free access to state of the art and fully working Machine Learning technology has had on transforming my quality of life.  Everything I own and everything I am, I owe to the brilliance and benevolence of an open source community of the world's greatest minds working together for one simple purpose:

To make life better for as many people as possible  through the free exchange of ideas, information, and discoveries at the bleeding edge of innovation.

When I first understood the value of FOSS, it was when I downloaded the weights and code and ran that first detection model on salvaged desktop hardware and a used $5 usb web cam from a thrift store.  

The realization that I held in my own two hands, a technology that could (and did) empower countless successes in my own life, with ZERO paywall or "ethics" committee or academic policy or lobbied regulatory capture or other price-gouged socioeconomic tyrant gatekeeping or excluding me from leveraging it in any way I needed.. and that it was running *perfectly* on parts of 5+ year old computers that I LITERALLY pulled out of the trash behind my work.. 

That was the most incomprehensibly valuable realization I have ever had in my life.  I finally OWNED something with real, lasting value.  I didn't own my car, I didn't own my home, all of my work clothes and everything else I had paid for on credit cards that would have taken 17 years of payments to pay off.  I had medical debt, debt from school, debt from work.  I didn't own the money that paid to keep myself alive, which feels a lot like not even owning your own body (not being able to afford going to the doctor in the US is a common thing and it really sucks).  Through all of that, FOSS pulled through and was the tool of liberation I was able to use to claw my way out of a designed system of hopelessness, depression, and poverty.

I am so sorry for posting all of that, but these new laws that suggest banning the sharing of open source Machine Learning is the most terrifying news that I have heard in recent years.  How many others like myself will this policy cause to lose access to the same tools I was able to leverage to escape a world that is overwhelmed with regulation that SOLELY benefits the hoarded wealth of billionaires at the expense of the rest of the world?

I am eternally grateful for your work, and I am nearing a point where it is time to begin planning on how we need to respond to the restriction of emerging technologies to keep them in the hands of the people, and away from exclusive access by entities that seek the ill-gotten gains of regulatory capture.

Sorry for the long story here, and I look forward to reviewing the code upon it's release.  I hope this doesn't come off as too heated, I just want to get through to as many important peers in the field as possible on how much these changes in policy have the potential to harm a global public, or at the very least to share my own small story to convey the magnitude of the devastation that restrictive policies on this technology without a doubt would have had on my own life.  Global prosperity depends on continuing to openly exchange the most valuable of ideas; I am here and willing to help however I can to ensure we don't lose that.

**Comment by andzejsp** [comment] 2023-03-21 15:28
So, basically all the nuts and bolts will be presentable by the next year or two (pretrained weights). And i was excited to play around this year. 

Will it atleast run on 3090? Or will you you need a 100k GPU arrays to generate stuff?

**Comment by xl-sr** [comment] 2023-03-21 18:13
Hopefully, this year already! It runs at ~10 FPS on a 3090.

**Comment by xl-sr** [comment] 2023-03-31 10:40
Update for everyone: code is done, and the review is in the last stage. ETA: next week :)

**Closed** 2023-04-07 09:06 UTC
